version: "3.8"
services:
    backend:
        build: ./backend
        container_name: backend_container
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/app
            - /app/node_modules
